# Site settings
title: Profesijas
#email: gaohaoyang126@126.com
description: "Dati par profesijÄm"
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "/profesiju-glabatuve" # the subpath of your site, e.g. /blog/
url: "http://broksainis.github.io/profesiju-glabatuve/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  none
permalink: none

# Build settings
markdown: kramdown
comments: false

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
